version: "3"

services:
  web:
    build: ./web/.
    ports:
      - "3000:3000"
    environment:
      - "NEXT_PUBLIC_APP_URL=http://app:4200"
    command: yarn start
    depends_on:
      - app

  app:
    build: ./app/.
    ports:
      - "4200:4200"
    environment:
      - "API_URL=http://api:8080"
    command: yarn start
    depends_on:
      - api

  api:
    build: ./api/.
    ports:
      - "8080:8080"
    environment:
      - "MYSQL_HOST=db"
      - "MYSQL_PASSWORD=docker"
      - "JWT_SECRET=8b20a05a5c63fc495616095087ac74f2"
    command: java -jar target/api-0.0.1-SNAPSHOT.jar
    depends_on:
      - db

  db:
    image: "mysql:latest"
    container_name: indevo-db
    restart: always
    environment:
      - "MYSQL_DATABASE=mysql"
      - "MYSQL_ROOT_PASSWORD=docker"
    ports:
      - "3306:3306"
    volumes:
      - ./db-dump/:/docker-entrypoint-initdb.d
